# .github/workflows/python-run.yml
name: اجرای آنلاین کد پایتون
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کد از مخزن
        uses: actions/checkout@v6
      - name: راه‌اندازی پایتون
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: اجرای اسکریپت
        run: |
          ls -la
          python main.py
