name: 'SOCKS5 Proxy'

on:
  workflow_dispatch:

jobs:
  socks5-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SOCKS5 Proxy via Chisel
        uses: animmouse/socks5-proxy-actions@d2f39a427b050b940257b96bb8d70b11a7bf7ef8  # استفاده از commit hash معتبر
        with:
          cloudflared-tunnel: true
